# Generated by Django 3.2 on 2024-06-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
